# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDateTime', models.DateTimeField(auto_now=True)),
                ('bTopic', models.CharField(max_length=20)),
                ('bInfo', models.CharField(max_length=200)),
                ('bAddr', models.CharField(max_length=20)),
                ('bPersonType', models.CharField(max_length=20)),
                ('bArticleType', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'blogs',
            },
            managers=[
                ('bManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bType', models.CharField(max_length=20, unique=True)),
                ('bInfo', models.CharField(max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'blogType',
            },
            managers=[
                ('bManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crNickName', models.CharField(default='guest', max_length=20)),
                ('crDateTime', models.DateTimeField(auto_now=True)),
                ('crInfo', models.CharField(max_length=200)),
                ('crTopic', models.CharField(max_length=20)),
                ('crType', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('crUserId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User')),
            ],
            options={
                'db_table': 'chatRecords',
            },
            managers=[
                ('crManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dDateTime', models.DateTimeField(auto_now=True)),
                ('dTopic', models.CharField(max_length=20)),
                ('dInfo', models.CharField(max_length=200)),
                ('dAddr', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('dUserId', models.ManyToManyField(to='SitesApp.User')),
            ],
            options={
                'db_table': 'dataBank',
            },
            managers=[
                ('dManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rDateTime', models.DateTimeField(auto_now=True)),
                ('rTopic', models.CharField(max_length=20)),
                ('rInfo', models.CharField(max_length=200)),
                ('rAddr', models.CharField(max_length=20)),
                ('rImpo', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('rUserId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User')),
            ],
            options={
                'db_table': 'reviews',
            },
            managers=[
                ('rManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='bBlogTypeId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.BlogType'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='bUserId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User'),
        ),
    ]
