# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0002_auto_20180605_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cEmail',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uEmail',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
