# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0003_auto_20180605_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cIcon',
            field=models.ImageField(blank=True, default='think.jpg', null=True, upload_to=''),
        ),
    ]
