# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0004_auto_20180605_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord',
            name='vComIP',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='vPolls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uIP',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
