# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:54
from __future__ import unicode_literals

import SitesApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0005_auto_20180605_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bBlogTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.BlogType'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vCandidateId',
            field=models.FloatField(blank=True, null=True, verbose_name=SitesApp.models.Candidate),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vTypeId',
            field=models.FloatField(blank=True, null=True, verbose_name=SitesApp.models.VoteType),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vUserId',
            field=models.FloatField(blank=True, null=True, verbose_name=SitesApp.models.User),
        ),
    ]
