# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0006_auto_20180605_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='vCandidateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.Candidate'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.VoteType'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User'),
        ),
    ]
