# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0009_auto_20180606_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cAge',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cDeclaration',
            field=models.CharField(default='我就是我，不一样的烟火', max_length=300, verbose_name='口号'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cEmail',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cIcon',
            field=models.ImageField(blank=True, default='think.jpg', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cName',
            field=models.CharField(max_length=20, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cPinyin',
            field=models.CharField(default='', max_length=20, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cTimes',
            field=models.IntegerField(default=1, verbose_name='轮数'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cVotes',
            field=models.IntegerField(default=0, verbose_name='票数'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crDateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crInfo',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crNickName',
            field=models.CharField(default='guest', max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crTopic',
            field=models.IntegerField(verbose_name='给谁留言'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crType',
            field=models.IntegerField(verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='crUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User', verbose_name='发言人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vCandidateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.Candidate', verbose_name='投给谁'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vComIP',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='电脑IP'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vDate',
            field=models.DateField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vPolls',
            field=models.IntegerField(default=0, verbose_name='票数'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vTimes',
            field=models.IntegerField(default=1, verbose_name='轮数'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.VoteType', verbose_name='投票类型'),
        ),
        migrations.AlterField(
            model_name='voterecord',
            name='vUserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='vInfo',
            field=models.CharField(max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='vType',
            field=models.CharField(max_length=20, unique=True, verbose_name='类型'),
        ),
    ]
