# Generated by Django 2.0.6 on 2018-06-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0010_auto_20180606_2035'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voterecord',
            managers=[
            ],
        ),
    ]
