# Generated by Django 2.0.6 on 2018-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0011_auto_20180610_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='crDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
