# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0014_auto_20180612_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rAddr',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rContent',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rTopic',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='主题'),
        ),
    ]
