# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0015_auto_20180612_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rAddr',
        ),
        migrations.AddField(
            model_name='review',
            name='rRemark',
            field=models.IntegerField(default=1, verbose_name='备注(0:已办、1:待办、2:计划)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cVoteType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SitesApp.VoteType', verbose_name='投票类型'),
        ),
    ]
